- name: Install the Calibre package from flathub
  flatpak:
    name: com.calibre_ebook.calibre
    state: present
    method: system
  tags:
    - software
    - calibre
  when: ansible_facts['distribution'] == "Fedora"
  
- name: Install Calibre package from apt
  become: yes
  apt:
    name: calibre
    state: present
  tags:
    - software
    - calibre
  when: ansible_facts['distribution'] == "Ubuntu"
