- name: Install the Meld package from flathub for current user
  flatpak:
    name: org.gnome.meld
    state: present
    method: system
  tags:
    - software
    - meld
  when: ansible_facts['distribution'] == "Fedora"
  
- name: Install Meld package from apt
  become: yes
  apt:
    name: meld
    state: present
  tags:
    - software
    - meld
  when: ansible_facts['distribution'] == "Ubuntu"
