- name: install base software
  dnf:
    name:
      - nextcloud-desktop
    update_cache: yes
    state: latest
  tags:
    - software
    - nextcloud
  become: yes
  when: ansible_facts['distribution'] == "Fedora"

- name: Check if Nextcloud Documents directory exists
  stat:
    path: "/home/{{ ansible_facts['env']['USER'] }}/Nextcloud/Documents"
  register: result
  tags:
    - software
    - nextcloud

- name: Create Nextcloud Documents if it doesn't exist
  file:
    path: "/home/{{ ansible_facts['env']['USER'] }}/Nextcloud/Documents"
    state: directory
    owner: "{{ ansible_facts['env']['USER'] }}"
    group: "{{ ansible_facts['env']['USER'] }}"
    mode: 0775
  when: result.stat.exists == false
  tags:
    - software
    - nextcloud

- name: Remove Documents directory from Home
  file:
    path: "/home/{{ ansible_facts['env']['USER'] }}/Documents"
    state: absent
  register: removal
  tags:
    - software
    - nextcloud

- name: Create Documents symlink in Home
  file:
    path: "/home/{{ ansible_facts['env']['USER'] }}/Documents"
    state: link
    src: "/home/{{ ansible_facts['env']['USER'] }}/Nextcloud/Documents"
  become: yes
  tags:
    - software
    - nextcloud

- name: Check if Nextcloud Photos directory exists
  stat:
    path: "/home/{{ ansible_facts['env']['USER'] }}/Nextcloud/Photos"
  register: result
  tags:
    - software
    - nextcloud

- name: Create Nextcloud Photos if it doesn't exist
  file:
    path: "/home/{{ ansible_facts['env']['USER'] }}/Nextcloud/Photos"
    state: directory
    owner: "{{ ansible_facts['env']['USER'] }}"
    group: "{{ ansible_facts['env']['USER'] }}"
    mode: 0775
  when: result.stat.exists == false
  tags:
    - software
    - nextcloud

- name: Remove Pictures directory from Home
  file:
    path: "/home/{{ ansible_facts['env']['USER'] }}/Pictures"
    state: absent
  register: removal
  tags:
    - software
    - nextcloud

- name: Create Pictures symlink in Home
  file:
    path: "/home/{{ ansible_facts['env']['USER'] }}/Pictures"
    state: link
    src: "/home/{{ ansible_facts['env']['USER'] }}/Nextcloud/Photos"
  become: yes
  tags:
    - software
    - nextcloud
 