- name: Install the Remmina package from flathub for current user
  flatpak:
    name: org.remmina.Remmina
    state: present
    method: system
  tags:
    - software
    - remmina
  when: ansible_facts['distribution'] == "Fedora"

- name: Install the Remmina snap
  become: yes
  snap:
    name: remmina
    state: present
  tags:
    - software
    - remmina
  when: ansible_facts['distribution'] == "Ubuntu"
