- name: Install Syncthing
  package:
    name:
      - syncthing
    update_cache: yes
    state: latest
  tags:
    - syncthing
  become: yes

- name: Start syncthing automatically
  ansible.builtin.systemd:
    state: started
    name: syncthing.service
    enabled: true
    scope: user
  tags:
    - syncthing
