- name: Install the Thunderbird package from flathub for current user
  flatpak:
    name: org.mozilla.Thunderbird
    state: present
    method: system
  tags:
    - software
    - thunderbird
  when: ansible_facts['distribution'] == "Fedora"

- name: Install the Thunderbird snap
  become: yes
  snap:
    name: thunderbird
    state: present
  tags:
    - software
    - thunderbird
  when: ansible_facts['distribution'] == "Ubuntu"
