- name: Copy VS Code repo file
  copy:
    src: files/vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
    mode: '0644'
  become: yes
  tags: 
    - vscode

- name: Install VS Code
  dnf:
    name:
      - code
    update_cache: yes
    state: latest
  tags:
    - vscode
  become: yes
