- name: Copy VS Code repo file
  copy:
    src: files/vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
    mode: '0644'
  become: yes
  tags: 
    - vscode
  when: ansible_facts['distribution'] == "Fedora"

- name: Install VS Code on Fedora
  dnf:
    name:
      - code
    update_cache: yes
    state: latest
  tags:
    - vscode
  become: yes
  when: ansible_facts['distribution'] == "Fedora"
  
- name: Install VS Code on Ubuntu
  become: yes
  snap:
    name: code
    classic: true
  tags:
    - vscode
  when: ansible_facts['distribution'] == "Ubuntu"
