- hosts: all
  remote_user: navigator
  become_method: su
  become_user: root
  vars:
    ansible_ssh_args: "-C -o PreferredAuthentications=password"

  tasks:
    - name: Authorize personal SSH key for personal user
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

    - name: Ensure sudo is installed
      apt:
        pkg:
          - sudo
        update_cache: yes
      become: true

    - name: Update the navigator user
      user:
        name: "{{ ansible_user }}"
        shell: /bin/bash
        groups: "sudo"
        append: yes
      become: true

    - name: Set remote user as passwordless sudo
      template:
        src: ./templates/ansible-nopasswd.j2
        dest: "/etc/sudoers.d/ansible-nopasswd"
        owner: root
        group: root
        mode: 0644
      become: true
