---
- hosts: all
  become: no
  vars:
  tasks:

    - name: Prepare System
      include_tasks: tasks/system.yml
      tags:
        - system
        - directories
        - flatpak
        - gnome
        - drives

    - name: Install Software
      include_tasks: tasks/software.yml
      tags:
        - base
        - vscode
        - starship
        - bitwarden
        - nextcloud
        - calibre
        - remmina
        - syncthing
        - qownnotes
