---
- hosts: all
  become: no
  vars:
  tasks:

    - name: Prepare System
      include_tasks: tasks/system.yml
      tags:
        - directories
        - drives
        - flatpak
        - gnome
        - system

    - name: Install Software
      include_tasks: tasks/software.yml
      tags:
        - base
        - bitwarden
        - calibre
        - meld
        - nextcloud
        - qownnotes
        - remmina
        - starship
        - syncthing
        - terraform
        - thunderbird
        - vscode
