- hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  vars_files:
    - ./vars/main.yml
  tasks:
    - name: Create config directory for frigate
      file:
        path: /opt/appdata/frigate
        state: directory
        owner: "{{ docker_user_uid }}"
        group: "{{ docker_user_gid }}"
        mode: "0755"
      tags: 
        - install

    - name: Copy frigate config
      copy:
        src: ./files/frigate/config.yml
        dest: /opt/appdata/frigate/
        owner: "{{ docker_user_uid }}"
        group: "{{ docker_user_gid }}"
        mode: "0644"
      tags:
        - install
        - config

    - name: Add Bitwarden desktop file entry
      template:
        src: ./templates/frigate/config.yml.j2
        dest: /opt/appdata/frigate/config.yml
        owner: "{{ docker_user_uid }}"
        group: "{{ docker_user_gid }}"
        mode: "0644"
      tags:
        - install
        - config

    - name: Create frigate container
      docker_container:
        name: frigate
        image: ghcr.io/blakeblackshear/frigate:stable
        privileged: true
        userns_mode: host
        shm_size: "64M"
        env:
          FRIGATE_RTSP_PASSWORD: "frigate"
        devices:
          - /dev/dri:/dev/dri
          - /dev/bus/usb:/dev/bus/usb
        ports:
          - "5000:5000"
          - "8554:8554" # RTSP feeds
          - "8555:8555/tcp" # WebRTC over tcp
          - "8555:8555/udp" # WebRTC over udp
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /opt/appdata/frigate/config.yml:/config/config.yml
          - /mnt/nas/storage/recordings:/media/frigate
        mounts:
          - type: tmpfs
            target: /tmp/cache
            tmpfs_size: "1G"
        restart_policy: unless-stopped
        networks:
          - name: external
      tags: 
        - install

    - name: Remove frigate container
      docker_container:
        name: frigate
        state: absent
      tags:
        - remove
        - purge
    
    - name: Remove frigate config directory
      file:
        path: /opt/appdata/frigate
        state: absent
      tags:
        - purge

    - name: Restart frigate container
      docker_container:
        name: frigate
        restart: true
      tags:
        - config
