- hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  vars_files:
  tasks:
    - name: Create gotenberg container
      docker_container:
        name: gotenberg
        image: gotenberg/gotenberg:7
        ports:
          - "3000:3000"
        restart_policy: unless-stopped
        networks:
          - name: internal
        purge_networks: yes
        networks_cli_compatible: yes
      tags: 
        - install
    
    - name: Remove gotenberg container
      docker_container:
        name: gotenberg
        state: absent
      tags:
        - remove
        - purge
    
