- name: Install base software
  include_tasks: tasks/software/base.yml
  tags:
    - base

- name: Install VS Code
  include_tasks: tasks/software/vscode.yml
  tags:
    - vscode

- name: Install Starship
  include_tasks: tasks/software/starship.yml
  tags:
    - starship
